package entities

import (
	"time"

	"github.com/google/uuid"
)

type NeedStatus string

const (
	NeedStatusInProgress NeedStatus = "IN_PROGRESS"
	NeedStatusReady      NeedStatus = "READY"     // ready to be promoted to PR
	NeedStatusConverted  NeedStatus = "CONVERTED" // PR was created in the external system
	NeedStatusDiscarded  NeedStatus = "DISCARDED"
)

// Need represents the pre-funnel stage of a purchase: the buyer identifies
// materials, collects vendor quotations, and when everything is settled
// promotes the need so the requester can create the formal Purchase
// Requisition in the external workflow system.
type Need struct {
	ID uuid.UUID `gorm:"type:uuid;default:uuid_generate_v4();primaryKey"`

	// Public correlative number (e.g. NEED-2026-0001), unique, generated by
	// the DB through NeedCounter using a transaction + row locking.
	Number string `gorm:"type:varchar(32);uniqueIndex;not null"`

	// Free-text fields for now (Quinar does not yet have users or cost-center
	// domains). When those domains exist, migrate these to FKs.
	RequesterName string `gorm:"type:varchar(255);not null"`
	BuyerName     string `gorm:"type:varchar(255);not null"`
	CostCenter    string `gorm:"type:varchar(100)"`

	// Operational justification and required delivery date.
	Justification string     `gorm:"type:text"`
	RequiredDate  *time.Time `gorm:"type:date"`

	Status NeedStatus `gorm:"type:varchar(32);not null;default:'IN_PROGRESS'"`

	// Timestamp when the need was promoted ("Ready").
	PromotedAt *time.Time
	// Timestamp when the external system confirms the PR was created.
	ConvertedAt *time.Time

	IsActive bool `gorm:"default:true;not null"`

	// Line items of this need. Eager-loaded on reads so the client receives
	// the materials together with the need.
	Items []NeedItem `gorm:"foreignKey:NeedID"`

	CreatedAt time.Time
	UpdatedAt time.Time
}
